#!/usr/bin/env sh

main() {
    if [ ! "$1" ]; then
        echo 'Required argument: action, see ebuild(1) for action list' >&2
        exit 1
    fi

    find . -not -ipath .git -type f -name \*.ebuild -exec ebuild {} "$1" \;
}

main "$@"
